#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XO_socket.Droid.Resource", IsApplication=true)]

namespace XO_socket.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050021
			public const int activity_main = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int bForgotPassword = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int bLogin = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int bRegistrationMain = 2131034149;
			
			// aapt resource value: 0x7f050000
			public const int dialog = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int dialog_changePass_etNewPassword = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int dialog_changePass_etPassword = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int dialog_changePass_etUsername = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int fragment_game = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int fragment_game_b1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int fragment_game_b2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int fragment_game_b3 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int fragment_game_b4 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int fragment_game_b5 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int fragment_game_b6 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int fragment_game_b7 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int fragment_game_b8 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int fragment_game_b9 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int fragment_game_bExit = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int fragment_game_tvStatusBar = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int fragment_lobby = 2131034130;
			
			// aapt resource value: 0x7f050019
			public const int fragment_lobby_bChange_PSW = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int fragment_lobby_bInvite = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int fragment_lobby_bLogin = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int fragment_lobby_bLogout = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int fragment_lobby_lvFreePlayersList = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int fragment_lobby_tvStatusBar = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int fragment_lobby_tvStatusBar_name = 2131034132;
			
			// aapt resource value: 0x7f050023
			public const int fragment_login = 2131034147;
			
			// aapt resource value: 0x7f050002
			public const int fragment_ra = 2131034114;
			
			// aapt resource value: 0x7f05001c
			public const int fragment_ra_bAuth = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int fragment_ra_bChangePass = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int fragment_ra_bReg = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int fragment_ra_etPassword = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int fragment_ra_etUsername = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int lobby_list_item = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int lobby_list_item_tvName = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int main_activity_fragment_placeholder = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int new_PSW = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int psw = 2131034151;
			
			// aapt resource value: 0x7f050001
			public const int textviewDialog = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_change_password = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_game = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_lobby = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_ra = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int lobby_list_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int mainmenu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int newpsw = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int button_auth = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int button_changePass = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int button_empty = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int button_exit = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int button_forgotPass = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int button_invite = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int button_login = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int button_logout = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int button_reg = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int edittext_newPassword = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int edittext_password = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int edittext_username = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int lobby_list_item_name = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int textview_lobby_statusbar = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int textview_lobby_statusbar_name = 2130968591;
			
			// aapt resource value: 0x7f04000b
			public const int textview_statusbar = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
